api_platform:
    title: Simple RESTFul API sample
    version: 1.0.0
    formats:
        json: [ 'application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
